# $OpenBSD$

COMMENT =	terminal client for telegram

MODPY_EGG_VERSION =	0.7.0

DISTNAME =	tg-${MODPY_EGG_VERSION}

CATEGORIES =	net

HOMEPAGE =	https://github.com/paul-nameless/tg

# Public domain
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_VERSION =		${MODPY_DEFAULT_VERSION_3}

RUN_DEPENDS =		net/py-telegram=0.13.0

.include <bsd.port.mk>
