# $OpenBSD$

COMMENT =	terminal client for Telegram

MODPY_EGG_VERSION =	0.8.0

DISTNAME =	tg-${MODPY_EGG_VERSION}

CATEGORIES =	net

HOMEPAGE =	https://github.com/paul-nameless/tg

# Public Domain
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_VERSION =		${MODPY_DEFAULT_VERSION_3}

RUN_DEPENDS =		net/py-telegram

.include <bsd.port.mk>
